<?php require('template/header.phtml') ?>               <!--Requiring header-->

<!--Css for the about us page-->
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
        }

        html {
            box-sizing: border-box;
        }

        *, *:before, *:after {
            box-sizing: inherit;
        }

        .column {
            float: left;
            width: 33.3%;
            margin-bottom: 16px;
            padding: 0 8px;
        }

        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            margin: 8px;
        }

        .about-section {
            padding: 50px;
            text-align: center;
            background-color: #474e5d;
            color: white;
        }

        .container {
            padding: 0 16px;
        }

        .container::after, .row::after {
            content: "";
            clear: both;
            display: table;
        }

        .title {
            color: grey;
        }

        .button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
        }

        .button:hover {
            background-color: #555;
        }

        @media screen and (max-width: 650px) {
            .column {
                width: 100%;
                display: block;
            }
        }
    </style>
</head>
<body>

<!--html for the about us page-->
<div class="about-section">
    <h1>About Us Page</h1>
    <p>We are the KRM developers from salford university</p>
    <p>Currently set a project by Kim to make a web application where users can submit there project ideas</p>
</div>

<!--Our team section-->
<h2 style="text-align:center">Our Team</h2>
<div class="row">
    <div class="column">
        <div class="card">
            <img src="../images/awais.jpg" alt="Jane" style="width:100%">
            <div class="container">
                <h2>Awais Tasleem</h2>
                <p class="title">Team leader</p>
                <p>I am the team leader currrently managing my SPAT group</p>
                <p>awaist7860@hotmail.com</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="../images/sammie.jpg" alt="Mike" style="width:100%">
            <div class="container">
                <h2>Sammi</h2>
                <p class="title">Backend Developer</p>
                <p>Currently a backend developer for this project</p>
                <p>sammiemussawer@hotmail.com</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="../images/naz.jpg" alt="Mike" style="width:100%">
            <div class="container">
                <h2>Naz</h2>
                <p class="title">Frontend Developer</p>
                <p>Currently a frontend developer for this project</p>
                <p>Nazmul2727@hotmail.co.uk</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="../images/hamaad.jpg" alt="Mike" style="width:100%">
            <div class="container">
                <h2>Hamaad</h2>
                <p class="title">Frontend Developer</p>
                <p>Currently a frontend developer for this project</p>
                <p>hamadchaudrey@gmail.com</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
    </div>

</body>
</html>


<?php require('template/footer.phtml') ?>               <!--Requiring footer-->