<?php require('template/header.phtml') ?>               <!--Requiring header-->


<!--Carousal added to make a slide show image-->
<div id= "demo" class="carousel slide" data-ride="carousel">
    <ul class="carousel-indicators">


        <!--Slideshow which transactions from one picture to another-->
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="images/networkinfrastructure.jpg" alt="networkinfrastructure" width="1000" height="1000">
        <div class="carousel-caption">
            <h3>IT Infrastructure</h3>
            <p>Purchase yours now!</p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="images/ITSecurity.jpg" alt="ITSecurity" width="1000" height="1000">
        <div class="carousel-caption">
            <h3>IT Security</h3>
            <p>Purchase yours now!</p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="images/softwaredevelopmentjpg.jpg" alt="softwaredevelopmentjpg" width="1000" height="1000">
        <div class="carousel-caption">
            <h3>IT Software Development</h3>
            <p>Purchase yours now!</p>
        </div>
    </div>
</div>
<a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
</a>
<a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
</a>
</div>

<!--About Us Section-->
<section class="my-5"
<div class="py-5"
<div>
    <h2 class="text-center"> About Us</h2>
</div>

<!--adding the text to the about us section-->
<div class="container-fluid"
<div class="row"
<p> Active in the secondment of IT specialists for over 20 years. We focus on the niche
    market within ICT.</p>
<p>Specialists in the field of infrastructure, security, (software)</p>
</div
</div>
</div>

<!--This is adding the text to the where we are based and how does it work section-->
<section class="my-5"
<div class="how-header"
<div>
    <h2 class="text-center"> Where are we based & how does it work?</h2>
    <p> We are based in Amsterdam and it works by registering and once logged in you can submit a application</p>
    <p>It is as simple as that!</p>
</div>
</div>
</section>

<!--This is the popular categories images section where I show the popular cars for auction-->
<div class="Popular categories container">
    <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0"><strong> Popular professional services</strong></h1>
    <hr class="popularcategoryimages">
    <div class="row text-center text-lg-left">

        <div class="col-lg-3 col-md-4 col-6">
            <a href="" class="d-block mb-4 h-100">
                <img class="image-fluid img-thumbnail" src="images/itinfrastructure.jpg" alt="">
                <p>Infrastructure Design</p>
            </a>
        </div>

        <div class="col-lg-3 col-md-4 col-6">
            <a href="../index.php" class="d-block mb-4 h-100">
                <img class="img-fluid img-thumbnail" src="images/hacking.jpg" alt="">
                <p>Hacking</p>
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-6">
            <a href="../index.php" class="d-block mb-4 h-100">
                <img class="img-fluid img-thumbnail" src="images/dataentry.jpg" alt="">
                <p>Data entry</p>
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-6">
            <a href="../index.php" class="d-block mb-4 h-100">
                <img class="img-fluid img-thumbnail" src="images/programming.jpg" alt="">
                <p>Programming</p>
            </a>
        </div>
    </div>
</div>

<!--This is the how it works section-->
<div class="howitworkstitle">
    <div class="container">
        <div class="title">
            <h2>How it works</h2>
        </div>

        <!--This is the text for the bid, win and enjoy section-->
        <div class="bodytext1">
            <!--<div id="whatever">-->
            <div class="project-model">
                <h3>Have a project?</h3>
                <p>Sign up to submit your project</p>
            </div>
            <div class="win-model">
                <h3>Submit the project</h3>
                <p>Once you login, you will be able to submit the<strong> project </strong></p>
            </div>
            <div class="discovery-model">
                <h3>What happens next?</h3>
                <p>The project will be submitted to projects@krm.nl</p>
            </div>
        </div>
    </div>
</div>
</div>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    </tbody>
    </table>
</form>
</form>

<?php require('template/footer.phtml') ?>               <!--Requiring footer-->



