<?php require('template/header.phtml') ?>               <!--Requiring header-->


<!--Login Form which is used to allow users to login-->
<form action="controller/signin.php" method="post">
    <div class="imgcontainer">
        <img src="toy1.jpg" alt="Avatar" class="avatar">
    </div>

    <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>

        <button type="submit">Login</button>
        <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
    </div>

    <!--Cancel button and forgot password section-->
    <div class="container" style="background-color:#f1f1f1">
        <button type="button" class="cancelbtn">Cancel</button>
        <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
</form>


<?php require_once ('../Views/template/footer.phtml'); ?>             <!--Requiring footer-->