<?php require(__DIR__ . '/../../Views/template/header.phtml') ?>               <!--Requiring header-->

<!--CSS for create auction-->
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: black;
        }

        * {
            box-sizing: border-box;
        }

        /* Add padding to containers */
        .container {
            padding: 16px;
            background-color: white;
        }

        /* Full-width input fields */
        textarea, input[type=text], input[type=password] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f1f1f1;
        }

        textarea:focus, input[type=text]:focus, input[type=password]:focus {
            background-color: #ddd;
            outline: none;
        }

        /* Overwrite default styles of hr */
        hr {
            border: 1px solid #f1f1f1;
            margin-bottom: 25px;
        }

        /* Set a style for the submit button */
        .registerbtn {
            background-color: #4CAF50;
            color: white;
            padding: 16px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

        .registerbtn:hover {
            opacity: 1;
        }

        /* Add a blue text color to links */
        a {
            color: dodgerblue;
        }

        /* Set a grey background color and center the text of the "sign in" section */
        .signin {
            background-color: #f1f1f1;
            text-align: center;
        }
    </style>
</head>
<body>

<!--Create auction HTML-->
<form action="createAuction.php" method="post" enctype="multipart/form-data">
    <div class="container">
        <h1>Create Auction</h1>
        <p>Please fill in this form to create an auction.</p>
        <hr>

        <!--Gives error message if form is not filled correctly-->
        <?php if(isset($_GET["error"])):?>
            <div class="alert alert-warning" role="alert">
                <?=$_GET["error"]?>
            </div>
        <?php endif; ?>

        <!--Title section-->
        <div>
            <label for="title"><b>Title</b></label>
            <input type="text" placeholder="Enter Title" name="title" id="title" required>
        </div>

        <!--Description section-->
        <div>
            <label for="description"><b>Description</b></label>
            <div>
                <textarea type="text" placeholder="Enter Description" name="description" id="description" rows="3" required></textarea>
            </div>
        </div>
        <div>
            <label for="title"><b>Price</b></label>
            <input type="number" placeholder="Enter Title" name="price" id="title" required>
        </div>

        <div>
            <label for="description"><b>Category</b></label>
            <div>
                <select name="category">
                    <option value="Car">
                        Car
                    </option>
                    <option value="furniture">
                        furniture
                    </option>
                    <option value="electronics">
                        electronics
                    </option>
                    <option value="games">
                        games
                    </option>
                    <option value="Book">
                        Book
                    </option>
                    <option value="Art">
                        Art
                    </option>
                </select>
            </div>
        </div>

        <!--Image Section-->
        <div>
            <label for="image"><b>Image</b></label>
            <div>
                <input type="file" name="image" id="image" accept="image/*" required>
            </div>
        </div>
        <hr>

        <!--Submit Button Section-->
        <button type="submit" name="sbt" class="registerbtn">Submit</button>
    </div>
</form>

</body>
</html>

<?php require(__DIR__ . '/../Views/template/footer.phtml') ?>               <!--Requiring the footer-->
