<!--Using Bootstrap Template-->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Group 11 SPAT Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
</head>
<body>

<!--Main Footer-->
<footer class="mainfooter" role="contentinfo">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4>KRM</h4>
                        <ul class="list-unstyled">
                            <li><a href="#"></a></li>
                            <li>This website was made by</a></li>
                            <li>Group 11 SPAT team</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4>Links</h4>
                        <ul class="list-unstyled">
                            <li><a href="controller/viewAuctions.php">About Us</a></li>
                            <li><a href="controller/viewAuctions.php">Create A project</a></li>
                            <li><a href="controller/viewAuctions.php">View my project</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <!--Column2-->
                    <div class="footer-pad">
                        <h4>Links</h4>
                        <ul class="list-unstyled">
                            <li><a href="controller/viewAuctions.php">Social media</a></li>
                            <li><a href="controller/viewAuctions.php">Jobs</a></li>
                            <li><a href="controller/viewAuctions.php">Contact Us</a></li>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <!--Follow us section-->
                    <h4>Follow Us</h4>
                    <ul class="social-network social-circle">
                        <li><a href="www.facebook.com" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="www.instagram.com" class="icoLinkedin" title="Linkedin"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="www.youtube.com" class="icoLinkedin" title="Linkedin"><i class="fa fa-youtube"></i></a></li>
                        <li><a href="www.twitter.com" class="icoLinkedin" title="Linkedin"><i class="fa fa-twitter"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 copy">
                    <p class="text-center">&copy; Copyright 2020 - KRM - This site was made by group 11 SPAT team</p>
                </div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>