
<!DOCTYPE html>
<html lang="en">
<head>

    <!--Using bootstrap template-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="../css/my-style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    </head>
    <body>

    <!--Login Model-->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <form method="post" action="../../controller/login.php">
                        <div class="container">
                            <label for="uname"><b>Username</b></label>
                            <input type="text" placeholder="Enter Email" name="uname" required>
                            <label for="psw"><b>Password</b></label>
                            <input type="password" placeholder="Enter Password" name="psw" required>
                            <input type="hidden" name="url" value="<?php $_SERVER['REQUEST_URI']?>"/>
                            <label>Test: </label>
                            <label>What is 2 + 2</label>
                            <input type="text" name="test" id="test" required>
                            <button type="submit" class="loginbtn">Login </button>

                            <!--Error message is user doesnt provide right details-->
                            <?php
                                if(isset($_GET["error"])) {
                                    echo "<script>$('#loginModal').trigger('show')</script>";
                                    echo "<h3 class='text-danger'>" . $_GET["error"] . "</h3>";
                                }
                            ?>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!--Navigation Bar-->
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" >KRM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href=<?="http://" . $_SERVER["SERVER_NAME"] . ":8001"?>>Home <span class="sr-only">(current)</span></a>
                </li>

                <!--Logout Section-->
                <?php if(isset($_SESSION["id"])): ?>
                    <li class="nav-item">
                        <h4><?=$_SESSION["username"]?></h4>
                        <a class="nav-link" href="../../controller/logout.php">Logout</a>
                    </li>
                <?php else: ?>

                    <!--Register Section-->
                    <li class="nav-item">
                        <a class="nav-link" href="../../controller/register.php">Register</a>
                    </li>

                    <!--Login Button-->
                    <li class="nav-item">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">
                            Login
                        </button>
                    </li>
                <?php endif; ?>

                <li class="nav-item">
                    <div class="dropdown show">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenu" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Projects
                        </a>

                        <!--Drop down menu-->
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenu" role="menu">
                            <?php if(strpos($_SERVER["REQUEST_URI"], "controller")) :?>
                                <a class="dropdown-item" href="../../controller/createAuction.php">Create Project</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="../../viewAuctions.php">View Project</a>
                            <?php else: ?>
                                <a class="dropdown-item" href="../../controller/createAuction.php">Create Project</a>

                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="../../controller/viewAuctions.php">View Project</a>
                                <a class="dropdown-item" href="../../controller/bids.php">Bid List</a>
                            <?php endif; ?>
                        </div>
                    </div>
                  </li>

                <!--Search Button-->
            </ul>
                <!-- <form  action="--><?php //echo $_SERVER['PHP_SELF']; ?><!--" method="post" class="form-inline">-->
                    <form  action="../../controller/viewAuctions.php" method="post" class="form-inline">
                <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" name="searchButton" type="submit">Search</button>
            </form>
        </div>
    </nav>

    </head>
    </body>

